// Code generated by oaacli DO NOT EDIT.
// Code generated by oaacli DO NOT EDIT.
// Code generated by oaacli DO NOT EDIT.
package {{.Package}}
import (
	"{{.Module}}/internal/service/{{.Package}}/{{.Method}}"
	"github.com/go-playground/validator/v10"
	"github.com/oaago/cloud/logx"
	"github.com/oaago/server/oaa"
	"github.com/oaago/server/oaa/translator"
)

{{range $i, $method := .Upmet }}
// @Summary ping example
// @Schemes
// @Description do ping
// @Tags example
// @Accept json
// @Produce json
// @Success 200 {object} {{$.UpPackage}}{{$.UpMethod}}Res
// @Router /{{$.Package}}/{{$.Method}} [{{$method}}]
func {{$method}}{{$.UpPackage}}{{$.UpMethod}}Handler(c *oaa.Ctx) {
	// 实例化service
	{{$.Package}}Srv := {{$.Package}}.NewService{{$.UpPackage}}()
	if err := c.ShouldBind(&{{$.Package}}Srv.{{$.UpPackage}}{{$.UpMethod}}Req); err != nil {
		// 获取validator.ValidationErrors类型的errors
		errs, ok := err.(validator.ValidationErrors)
		if !ok {
			// 非validator.ValidationErrors类型错误直接返回
			c.Return(400, errs.Translate(translator.Trans))
			return
		}
		return
	}
	{{if eq $method "Get"}}
	err := {{$.Package}}Srv.{{$method}}{{$.UpPackage}}{{$.UpMethod}}Service()
	{{else if eq $method "Delete"}}
	err := {{$.Package}}Srv.{{$method}}{{$.UpPackage}}{{$.UpMethod}}Service()
	{{else}}
	{{$.UpPackage}}{{$.UpMethod}}Res, err := {{$.Package}}Srv.{{$method}}{{$.UpPackage}}{{$.UpMethod}}Service()
	logx.Logger.Info("{{$.UpPackage}}{{$.UpMethod}}数据请求成功", {{$.UpPackage}}{{$.UpMethod}}Res){{end}}
	if err != nil {
		c.Return(10006)
		return
	}
	c.Return(200, {{$.Package}}Srv.{{$.UpPackage}}{{$.UpMethod}}Res)
	return
}
{{end}}