package tpl

var ApiTPL = `// Code generated by oaacli DO NOT EDIT.
// Code generated by oaacli DO NOT EDIT.
// Code generated by oaacli DO NOT EDIT.
package {{.Package}}
import (
	"{{.Module}}/internal/service/{{.Package}}/{{.Method}}"
	"github.com/go-playground/validator/v10"
	"github.com/oaago/cloud/logx"
	"github.com/oaago/server/oaa"
	"github.com/oaago/server/oaa/translator"
)

// @Summary ping example
// @Schemes
// @Description do ping
// @Tags example
// @Accept json
// @Produce json
// @Success 200 {object} {{.UpPackage}}{{.UpMethod}}Res
// @Router /{{.Package}}/{{.Method}} [{{.Met}}]
func {{.UpPackage}}{{.UpMethod}}Handler(c *oaa.Ctx) {
	// 实例化service
	{{.Package}}Srv := {{.Package}}.NewService{{.UpPackage}}()
	if err := c.ShouldBind(&{{.Package}}Srv.{{.UpPackage}}{{.UpMethod}}Req); err != nil {
		// 获取validator.ValidationErrors类型的errors
		errs, ok := err.(validator.ValidationErrors)
		if !ok {
			// 非validator.ValidationErrors类型错误直接返回
			c.Return(400, errs.Translate(translator.Trans))
			return
		}
		return
	}
    {{.UpPackage}}{{.UpMethod}}Res, err := {{.Package}}Srv.{{.UpPackage}}{{.UpMethod}}Service()
	if err != nil {
		c.Return(10006)
		return
	}
	logx.Logger.Info("数据请求成功", {{.UpPackage}}{{.UpMethod}}Res)
	c.Return(200, {{.Package}}Srv.{{.UpPackage}}{{.UpMethod}}Res)
	return
}
`

var SRVTPL = `package {{.Package}}

func (u *{{.UpPackage}}) {{.UpPackage}}{{.UpMethod}}Service() ({{.UpPackage}}{{.UpMethod}}Res, error) {
	return u.{{.UpPackage}}{{.UpMethod}}Res,nil
}
`

var RPCSRVTPL = `package {{.Package}}
import (
	"context"
	rpc_{{.RpcName}}_{{.UpMethod}} "{{.Module}}/internal/api/rpc/{{.RpcName}}/{{.Method}}"
	"github.com/oaago/cloud/logx"
)
func (u *{{.UpPackage}}{{.UpMethod}}Type) {{.UpPackage}}{{.UpMethod}}Service(ctx context.Context, request *rpc_{{.RpcName}}_{{.UpMethod}}.{{.UpRpcName}}{{.UpMethod}}Request) (*rpc_{{.RpcName}}_{{.UpMethod}}.{{.UpRpcName}}{{.UpMethod}}Reply, error) {
	//TODO implement me
	logx.Logger.Info(request)
	// 调用其他rpc 服务的示例
	// 	res := rpc_fff_Ddd.NewRpcFffDddClient(rpc_fff_Ddd.RpcClientType{
	//		EtcdAddr:          "http://127.0.0.1:2379",
	//		RemoteServiceName: op.ConfigData.Server.Name,
	//	})
	//  c, cancel := context.WithTimeout(context.Background(), time.Second*2)
	//	resp, err := res.RpcFffDddService(c, &rpc_fff_Ddd.FffDddRequest{
	//		Name: "22222",
	//	})
	//  defer cancel()
	//	logx.Logger.Info(resp, err)
	return &rpc_{{.RpcName}}_{{.UpMethod}}.{{.UpRpcName}}{{.UpMethod}}Reply{}, nil
}
`

var TYPESTPL = `
package {{.Package}}

type {{.UpPackage}} struct {
	Service{{.UpPackage}}
	{{.UpPackage}}{{.UpMethod}}Res
  {{.UpPackage}}{{.UpMethod}}Req
}

type {{.UpPackage}}{{.UpMethod}}Res struct{}

type {{.UpPackage}}{{.UpMethod}}Req struct{}

type Service{{.UpPackage}} interface {
	//{{.Func}}  @Router /{{.Package}}/{{.Func}} [{{.Method}}]
	//{{.Func}}()
}

func NewService{{.UpPackage}}() *{{.UpPackage}} {
	return &{{.UpPackage}}{}
}
`

var DAOTYPESTPL = `
package {{.Package}}

type {{.UpPackage}} struct {

}
`

var RpcTYPESTPL = `
package {{.Package}}
import (
	{{.UpPackage}}{{.UpMethod}} "{{.Module}}/internal/api/rpc/{{.Package}}/{{.Method}}"
)
type {{.UpPackage}}{{.UpMethod}}Type struct {
	{{.UpPackage}}{{.UpMethod}}.Unimplemented{{.UpPackage}}{{.UpMethod}}Server
}

func NewService{{.UpPackage}}{{.UpMethod}}() *{{.UpPackage}}{{.UpMethod}}Type {
	return &{{.UpPackage}}{{.UpMethod}}Type{}
}
`

var ROUTERTPL = `// Code generated by oaacli DO NOT EDIT.
// Code generated by oaacli DO NOT EDIT.
// Code generated by oaacli DO NOT EDIT.
package router
import (
	"github.com/oaago/server/oaa"
	middleware_http "{{.Module}}/internal/middleware/http"
    {{range $index, $item := .MapHandlerMap}}
	{{$item.HttpDir}}{{$item.UpMethod}} "{{$item.Module}}/internal/api/http/{{$item.HttpDir}}/{{$item.Method}}" //{{$item}}
    {{end}}
)

func LoadRouterMap() oaa.MapHttpRoute {
	{{if eq .MiddlewareLen 0}}
	// Pid := middleware_http.NewPid()
	{{else}}  
	Pid := middleware_http.NewPid()
	{{end}}
	m := oaa.MapHttpRoute{
	{{range $index, $item := .MapHandlerMap}}
		"{{$item.Url}}": {
			{{range $index, $it := $item.Middleware}}Pid.{{$it}}{{end}}
			{{$item.HttpDir}}{{$item.UpMethod}}.{{$item.Handler}}Handler,
		},
	{{end}}
	}
	return m
}
`

var RPCROUTERTPL = `// Code generated by oaacli DO NOT EDIT.
// Code generated by oaacli DO NOT EDIT.
// Code generated by oaacli DO NOT EDIT.
package router
import (
	"context"
	"github.com/grpc-ecosystem/grpc-gateway/v2/runtime"
	"github.com/oaago/cloud/op"
	"google.golang.org/grpc"
	grpcmiddleware "github.com/grpc-ecosystem/go-grpc-middleware"
	grpcauth "github.com/grpc-ecosystem/go-grpc-middleware/auth"
	grpczap "github.com/grpc-ecosystem/go-grpc-middleware/logging/zap"
	"github.com/grpc-ecosystem/go-grpc-middleware/ratelimit"
	grpcrecovery "github.com/grpc-ecosystem/go-grpc-middleware/recovery"
	grpcctxtags "github.com/grpc-ecosystem/go-grpc-middleware/tags"
	grpcopentracing "github.com/grpc-ecosystem/go-grpc-middleware/tracing/opentracing"
	grpc_validator "github.com/grpc-ecosystem/go-grpc-middleware/validator"
	grpcprometheus "github.com/grpc-ecosystem/go-grpc-prometheus"
	"google.golang.org/grpc/codes"
	"github.com/oaago/cloud/logx"
	"google.golang.org/protobuf/encoding/protojson"
	"strconv"
{{range $index, $item := .MapHandlerMap}}
	{{$item.UpPackage}}{{$item.UpMethod}} "{{$item.Module}}/internal/api/rpc/{{$item.Package}}/{{$item.Method}}"
	SRV{{$item.UpPackage}}{{$item.UpMethod}} "{{$item.Module}}/internal/service/rpc/{{$item.Package}}/{{$item.Method}}"
{{end}}
)

type alwaysPassLimiter struct{}
type Recovery struct {
}

func (*alwaysPassLimiter) Limit() bool {
	return false
}

func (re Recovery) RecoveryInterceptor() grpcrecovery.Option {
	return grpcrecovery.WithRecoveryHandler(func(p interface{}) (err error) {
		return grpc.Errorf(codes.Unknown, "panic triggered: %v", p)
	})
}

func RegisterRpcGenRouter() *grpc.Server {
	limiter := &alwaysPassLimiter{}
	recovery := &Recovery{}
	s := grpc.NewServer(
		grpc.StreamInterceptor(grpcmiddleware.ChainStreamServer(
			grpczap.StreamServerInterceptor(logx.Logx),
			grpcctxtags.StreamServerInterceptor(),
			grpcopentracing.StreamServerInterceptor(),
			grpcprometheus.StreamServerInterceptor,
			grpcauth.StreamServerInterceptor(func(ctx context.Context) (context.Context, error) {
				return nil, nil
			}),
			ratelimit.StreamServerInterceptor(limiter),
			grpc_validator.StreamServerInterceptor(),
			grpcrecovery.StreamServerInterceptor(recovery.RecoveryInterceptor()),
		)),
		grpc.UnaryInterceptor(grpcmiddleware.ChainUnaryServer(
			grpczap.UnaryServerInterceptor(logx.Logx),
			grpcctxtags.UnaryServerInterceptor(),
			grpcopentracing.UnaryServerInterceptor(),
			grpcprometheus.UnaryServerInterceptor,
			ratelimit.UnaryServerInterceptor(limiter),
			grpcauth.UnaryServerInterceptor(func(ctx context.Context) (context.Context, error) {
					return nil, nil
			}),
			grpc_validator.UnaryServerInterceptor(),
			grpcrecovery.UnaryServerInterceptor(recovery.RecoveryInterceptor()),
		)),
	)
	ctx := context.Background()
	mux := runtime.NewServeMux(runtime.WithMarshalerOption(runtime.MIMEWildcard, &runtime.JSONPb{MarshalOptions: protojson.MarshalOptions{UseEnumNumbers: true, UseProtoNames: true}}))
	var err error
{{range $index, $item := .MapHandlerMap}}
	err = {{$item.UpPackage}}{{$item.UpMethod}}.Register{{$item.UpPackage}}{{$item.UpMethod}}GWFromEndpoint(ctx, mux, "localhost:" + strconv.Itoa(op.ConfigData.Server.Port+1000), []grpc.DialOption{grpc.WithInsecure()})
	{{$item.UpPackage}}{{$item.UpMethod}}.Register{{$item.UpPackage}}{{$item.UpMethod}}Server(s, SRV{{$item.UpPackage}}{{$item.UpMethod}}.NewService{{$item.UpPackage}}{{$item.UpMethod}}()){{end}}
	return s
}`

var MAINTPL = `package main

import (
	"%package%/internal/consts"
	"%package%/internal/router"
	docs "%package%/docs"
	_ "github.com/oaago/cloud/logx"
	"github.com/oaago/cloud/op"
	_ "github.com/oaago/cloud/preload"
	"github.com/oaago/server/oaa"
)

func main() {
	op.ConfigData.CodeMap = consts.CODE
	r := oaa.NewRouter(&oaa.ConfigRouter{
		MapHttpRoute: router.LoadRouterMap,
		MapRpcRoute:  router.RegisterRpcGenRouter,
	})
	docs.SwaggerInfo.BasePath = op.ConfigData.Server.BasePath
	oaa.Start(r)
}
`
var DEFIENDJSON = `{
  "http": [
		"get@/app/bbb",
		"post@/ccc/bbb|TT"
  ],
  "rpc": [
		"get&/ccc/ddd",
		"get&/fff/ddd"
  ]
}
`

var CONFIGTPL = `server:
  name: %package%
  port: 9932
  env: local
  version: 1.0
  weight: 1
mysql:
  enable: true
  a: root:root@tcp(127.0.0.1:3306)/a
nacos:
  enable: true
  ipaddr: nacos.com
  logdir: ./nacos
  cachedir: ./nacos
  dataid: %package%
  group: %package%
kafka:
  consumer:
    enable: true
    nodes:
      - 0.0.0.0:9093
    topic:
      - TestComposeTopic
    groupid: qqqq
  producer:
    enable: true
    nodes:
      - 0.0.0.0:9093
    topic: TestComposeTopic
redis:
  enable: true
  addr: 127.0.0.1:6937
  password: 123456
  db: 1
logger:
  enablekafka: true
  path: ./logs
  name:  %package%
docker:
  harbor:
    url: 192.168.3.85:8088
`

var CODETPL = `package consts
var CODE = map[int]string{
	20000: "测试",
}
`

var PROTOTPL = `syntax = "proto3";

package rpc.{{.Package}}.{{.Method}};

// 多语言特定包名，用于源代码引用
option go_package = "rpc/{{.Package}}/{{.Method}}";
option java_multiple_files = true;
option java_package = "rpc/{{.Package}}/{{.Method}}";
option objc_class_prefix = "rpc/{{.Package}}/{{.Method}}";
import "github.com/mwitkow/go-proto-validators@v0.3.2/validator.proto";

// 描述该服务的信息
service {{.UpPackage}}{{.UpMethod}} {
  // 描述该方法的功能
  rpc Rpc{{.UpPackage}}{{.UpMethod}}Service ({{.UpPackage}}{{.UpMethod}}Request) returns ({{.UpPackage}}{{.UpMethod}}Reply);
}

message InnerMessage {
  // some_integer can only be in range (1, 100).
  int32 some_integer = 1 [(validator.field) = {int_gt: 0, int_lt: 100}];
  // some_float can only be in range (0;1).
  double some_float = 2 [(validator.field) = {float_gte: 0, float_lte: 1}];
}
message OuterMessage {
  // important_string must be a lowercase alpha-numeric of 5 to 30 characters (RE2 syntax).
  string important_string = 1 [(validator.field) = {regex: "^[a-z]{2,5}$"}];
  InnerMessage inner = 2 [(validator.field) = {msg_exists : true}];
}
// Hello请求参数
message {{.UpPackage}}{{.UpMethod}}Request {
  // 用户名字
  string name = 1;
}
// Hello返回结果
message {{.UpPackage}}{{.UpMethod}}Reply {
  // 结果信息
  string message = 1;
}`

var MIDTPL = `package middleware

import (
"fmt"
"github.com/oaago/server/oaa"
)

type Pid oaa.PartMiddleware
type Gid oaa.GlobalMiddleware

func NewPid() Pid {
	return Pid{}
}
func NewGid() Gid {
	return Gid{}
}

func (Pid) TT(c *oaa.Ctx) {
	fmt.Println("PartMiddleware")
	c.Next()
	fmt.Println("2222")
}

func (Gid) BB(c*oaa.Ctx) {
	fmt.Println("GlobalMiddleware")
	c.Next()
	fmt.Println("4444")
}`

var DAOTPL = `
package dao_{{.Package}}

import (
	"{{.Module}}/internal/model/{{.Package}}_model"
	"{{.Module}}/internal/model/{{.Package}}_query"
	"github.com/oaago/cloud/mysql"
	"github.com/oaago/cloud/redis"
	"gorm.io/gorm"
)

type {{.UpMethod}}Dao struct {
	DB      *gorm.DB
	Query   *{{.Package}}_query.Query
	Table   string
	Columns {{.Package}}_model.{{.UpMethod}}
	RedisClient redis.Cli
}

var (
	model = {{.Package}}_model.{{.UpMethod}}{}
	{{.UpMethod}} = {{.UpMethod}}Dao{
		DB:      mysql.GetDBByName("{{.Package}}"),
		Query:   {{.Package}}_query.Use(mysql.GetDBByName("{{.Package}}")),
		Table:   model.TableName(),
		Columns: {{.Package}}_model.{{.UpMethod}}{},
		RedisClient: *redis.RedisClient,
	}
)
`
var DockerFile = `# Code generated by oaacli DO NOT EDIT.
# Code generated by oaacli DO NOT EDIT.
# Code generated by oaacli DO NOT EDIT.
# 基础镜像，基于golang的alpine镜像构建--编译阶段
FROM golang:alpine AS builder
# 作者
MAINTAINER oaago
# 全局工作目录
WORKDIR /data/{{.Module}}
# 把运行Dockerfile文件的当前目录所有文件复制到目标目录
COPY . /data/{{.Module}}
# 环境变量
#  用于代理下载go项目依赖的包
ENV GOPROXY https://goproxy.cn,direct
# 编译，关闭CGO，防止编译后的文件有动态链接，而alpine镜像里有些c库没有，直接没有文件的错误
RUN GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build -ldflags="-w -s" main.go

# 使用alpine这个轻量级镜像为基础镜像--运行阶段
FROM alpine AS runner
# 全局工作目录
WORKDIR /data/{{.Module}}
# 复制编译阶段编译出来的运行文件到目标目录
COPY --from=builder /data/{{.Module}}/main .
# 复制编译阶段里的config文件夹到目标目录
COPY --from=builder /data/{{.Module}}/app.yaml ./
# 将时区设置为东八区
RUN echo "https://mirrors.aliyun.com/alpine/v3.8/main/" > /etc/apk/repositories \
    && echo "https://mirrors.aliyun.com/alpine/v3.8/community/" >> /etc/apk/repositories \
    && apk add --no-cache tzdata \
    && cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime  \
    && echo Asia/Shanghai > /etc/timezone \
    && apk del tzdata
# 需暴露的端口
EXPOSE {{.Port}}
# 可外挂的目录
VOLUME ["/data/{{.Module}}","/data/{{.Module}}/logs"]
# docker run命令触发的真实命令(相当于直接运行编译后的可运行文件)
ENTRYPOINT ["./main"]`

var PowerprotoTpl = `scopes:
  - ./rpc
protoc: v3.20.1
protocWorkDir: ""
plugins:
  protoc-gen-go: google.golang.org/protobuf/cmd/protoc-gen-go@v1.28.0
  protoc-gen-go-grpc: google.golang.org/grpc/cmd/protoc-gen-go-grpc@ad51f572fd270f2323e3aa2c1d2775cab9087af2
  protoc-gen-grpc-gateway: github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-grpc-gateway@v2.11.0
  protoc-gen-openapiv2: github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2@v2.11.0
  protoc-gen-oaago: github.com/oaago/protoc-gen-oaago@v0.0.2
  protoc-gen-govalidators: github.com/mwitkow/go-proto-validators/protoc-gen-govalidators@v0.3.2
  protoc-gen-doc: github.com/pseudomuto/protoc-gen-doc/cmd/protoc-gen-doc@v1.5.1
  protoc-go-inject-tag: github.com/favadi/protoc-go-inject-tag@v1.3.0
repositories:
  GOGO_PROTOBUF: https://github.com/gogo/protobuf@226206f39bd7276e88ec684ea0028c18ec2c91ae
  GOOGLE_APIS: https://github.com/googleapis/googleapis@75e9812478607db997376ccea247dd6928f70f45
options:
  - --go_out=./internal/api
  - --go-grpc_out=./internal/api
  - --go-grpc_opt=paths=source_relative
  - --oaago_out=paths=source_relative:./internal/api
  - --go_opt=paths=source_relative
  - --grpc-gateway_out=./internal/api
  - --grpc-gateway_opt=paths=source_relative
  - --grpc-gateway_opt=generate_unbound_methods=true
  - --grpc-gateway_opt=logtostderr=true
  - --grpc-gateway_opt=register_func_suffix=GW
  - --grpc-gateway_opt=allow_delete_body=true
  - --govalidators_out=paths=source_relative:./internal/api
  - --doc_out=./docs
  - --openapiv2_out=./docs
importPaths:
  - .
  - $GOPATH
  - $GOPATH/src
  - $POWERPROTO_INCLUDE
  - $SOURCE_RELATIVE
  - $GOOGLE_APIS/github.com/googleapis/googleapis
  - $GOGO_PROTOBUF
  - $GOPATH/pkg/mod
  - ./rpc
postActions: []
postShell: ""
#               cd example
#               protoc -I ./ -I ./contract \
#               --proto_path=$GOPATH/src \
#               --proto_path=${GOPATH}/pkg/mod \
#               --proto_path=./contract \
#               --govalidators_out=paths=source_relative:./apis/ \
#               --go_out=paths=source_relative:./apis/ \
#               --go-grpc_out=./apis --go-grpc_opt=paths=import \
#               --oaago_out=./apis \
#               --oaago_opt=paths=import \
#               --grpc-gateway_out ./apis --grpc-gateway_opt paths=import \
#               --grpc-gateway_opt logtostderr=true \
#               --grpc-gateway_opt generate_unbound_methods=true \
#               --grpc-gateway_opt register_func_suffix=GW \
#               --grpc-gateway_opt allow_delete_body=true \
#               --doc_out=./docs \
#               --doc_opt=html,index.html \
#               --openapiv2_out ./docs --openapiv2_opt logtostderr=true \
#               ./contract/app/app.proto

`
